//Use the same rest countries and print all countries name, region, sub region and population


var xhr=new XMLHttpRequest();
xhr.open("GET","https://raw.githubusercontent.com/rvsp/restcountries-json-data/master/res-countries.json");
xhr.send();

//listener
xhr.onload=function(){
//server will return response of the data
if(xhr.status>=200 && xhr.status<300){
   // console.log(this.response);
//convert raw data in javascript notation format
var data=JSON.parse(xhr.response);
//console.log(data);
for(var i=0; i<data.length; i++){
   console.log("COUNTRY NAME:"+data[i].name+","+"REGION:"+data[i].region+","+"SUB REGION:"+data[i].subregion+","+"POPULATION:"+data[i].population);
    //console.log(data[i]);
}
}else{
//you should print the error 
console.log("Data is not available");
}
}

/* RESULTS
COUNTRY NAME:Afghanistan,REGION:Asia,SUB REGION:Southern Asia,POPULATION:27657145
task2.js:17 COUNTRY NAME:Åland Islands,REGION:Europe,SUB REGION:Northern Europe,POPULATION:28875
task2.js:17 COUNTRY NAME:Albania,REGION:Europe,SUB REGION:Southern Europe,POPULATION:2886026
task2.js:17 COUNTRY NAME:Algeria,REGION:Africa,SUB REGION:Northern Africa,POPULATION:40400000
task2.js:17 COUNTRY NAME:American Samoa,REGION:Oceania,SUB REGION:Polynesia,POPULATION:57100
task2.js:17 COUNTRY NAME:Andorra,REGION:Europe,SUB REGION:Southern Europe,POPULATION:78014
task2.js:17 COUNTRY NAME:Angola,REGION:Africa,SUB REGION:Middle Africa,POPULATION:25868000
task2.js:17 COUNTRY NAME:Anguilla,REGION:Americas,SUB REGION:Caribbean,POPULATION:13452
task2.js:17 COUNTRY NAME:Antarctica,REGION:Polar,SUB REGION:,POPULATION:1000
task2.js:17 COUNTRY NAME:Antigua and Barbuda,REGION:Americas,SUB REGION:Caribbean,POPULATION:86295
task2.js:17 COUNTRY NAME:Argentina,REGION:Americas,SUB REGION:South America,POPULATION:43590400
task2.js:17 COUNTRY NAME:Armenia,REGION:Asia,SUB REGION:Western Asia,POPULATION:2994400
task2.js:17 COUNTRY NAME:Aruba,REGION:Americas,SUB REGION:Caribbean,POPULATION:107394
task2.js:17 COUNTRY NAME:Australia,REGION:Oceania,SUB REGION:Australia and New Zealand,POPULATION:24117360
task2.js:17 COUNTRY NAME:Austria,REGION:Europe,SUB REGION:Western Europe,POPULATION:8725931
task2.js:17 COUNTRY NAME:Azerbaijan,REGION:Asia,SUB REGION:Western Asia,POPULATION:9730500
task2.js:17 COUNTRY NAME:Bahamas,REGION:Americas,SUB REGION:Caribbean,POPULATION:378040
task2.js:17 COUNTRY NAME:Bahrain,REGION:Asia,SUB REGION:Western Asia,POPULATION:1404900
task2.js:17 COUNTRY NAME:Bangladesh,REGION:Asia,SUB REGION:Southern Asia,POPULATION:161006790
task2.js:17 COUNTRY NAME:Barbados,REGION:Americas,SUB REGION:Caribbean,POPULATION:285000
task2.js:17 COUNTRY NAME:Belarus,REGION:Europe,SUB REGION:Eastern Europe,POPULATION:9498700
task2.js:17 COUNTRY NAME:Belgium,REGION:Europe,SUB REGION:Western Europe,POPULATION:11319511
task2.js:17 COUNTRY NAME:Belize,REGION:Americas,SUB REGION:Central America,POPULATION:370300
task2.js:17 COUNTRY NAME:Benin,REGION:Africa,SUB REGION:Western Africa,POPULATION:10653654
task2.js:17 COUNTRY NAME:Bermuda,REGION:Americas,SUB REGION:Northern America,POPULATION:61954
task2.js:17 COUNTRY NAME:Bhutan,REGION:Asia,SUB REGION:Southern Asia,POPULATION:775620
task2.js:17 COUNTRY NAME:Bolivia (Plurinational State of),REGION:Americas,SUB REGION:South America,POPULATION:10985059
task2.js:17 COUNTRY NAME:Bonaire, Sint Eustatius and Saba,REGION:Americas,SUB REGION:Caribbean,POPULATION:17408
task2.js:17 COUNTRY NAME:Bosnia and Herzegovina,REGION:Europe,SUB REGION:Southern Europe,POPULATION:3531159
task2.js:17 COUNTRY NAME:Botswana,REGION:Africa,SUB REGION:Southern Africa,POPULATION:2141206
task2.js:17 COUNTRY NAME:Bouvet Island,REGION:,SUB REGION:,POPULATION:0
task2.js:17 COUNTRY NAME:Brazil,REGION:Americas,SUB REGION:South America,POPULATION:206135893
task2.js:17 COUNTRY NAME:British Indian Ocean Territory,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:3000
task2.js:17 COUNTRY NAME:United States Minor Outlying Islands,REGION:Americas,SUB REGION:Northern America,POPULATION:300
task2.js:17 COUNTRY NAME:Virgin Islands (British),REGION:Americas,SUB REGION:Caribbean,POPULATION:28514
task2.js:17 COUNTRY NAME:Virgin Islands (U.S.),REGION:Americas,SUB REGION:Caribbean,POPULATION:114743
task2.js:17 COUNTRY NAME:Brunei Darussalam,REGION:Asia,SUB REGION:South-Eastern Asia,POPULATION:411900
task2.js:17 COUNTRY NAME:Bulgaria,REGION:Europe,SUB REGION:Eastern Europe,POPULATION:7153784
task2.js:17 COUNTRY NAME:Burkina Faso,REGION:Africa,SUB REGION:Western Africa,POPULATION:19034397
task2.js:17 COUNTRY NAME:Burundi,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:10114505
task2.js:17 COUNTRY NAME:Cambodia,REGION:Asia,SUB REGION:South-Eastern Asia,POPULATION:15626444
task2.js:17 COUNTRY NAME:Cameroon,REGION:Africa,SUB REGION:Middle Africa,POPULATION:22709892
task2.js:17 COUNTRY NAME:Canada,REGION:Americas,SUB REGION:Northern America,POPULATION:36155487
task2.js:17 COUNTRY NAME:Cabo Verde,REGION:Africa,SUB REGION:Western Africa,POPULATION:531239
task2.js:17 COUNTRY NAME:Cayman Islands,REGION:Americas,SUB REGION:Caribbean,POPULATION:58238
task2.js:17 COUNTRY NAME:Central African Republic,REGION:Africa,SUB REGION:Middle Africa,POPULATION:4998000
task2.js:17 COUNTRY NAME:Chad,REGION:Africa,SUB REGION:Middle Africa,POPULATION:14497000
task2.js:17 COUNTRY NAME:Chile,REGION:Americas,SUB REGION:South America,POPULATION:18191900
task2.js:17 COUNTRY NAME:China,REGION:Asia,SUB REGION:Eastern Asia,POPULATION:1377422166
task2.js:17 COUNTRY NAME:Christmas Island,REGION:Oceania,SUB REGION:Australia and New Zealand,POPULATION:2072
task2.js:17 COUNTRY NAME:Cocos (Keeling) Islands,REGION:Oceania,SUB REGION:Australia and New Zealand,POPULATION:550
task2.js:17 COUNTRY NAME:Colombia,REGION:Americas,SUB REGION:South America,POPULATION:48759958
task2.js:17 COUNTRY NAME:Comoros,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:806153
task2.js:17 COUNTRY NAME:Congo,REGION:Africa,SUB REGION:Middle Africa,POPULATION:4741000
task2.js:17 COUNTRY NAME:Congo (Democratic Republic of the),REGION:Africa,SUB REGION:Middle Africa,POPULATION:85026000
task2.js:17 COUNTRY NAME:Cook Islands,REGION:Oceania,SUB REGION:Polynesia,POPULATION:18100
task2.js:17 COUNTRY NAME:Costa Rica,REGION:Americas,SUB REGION:Central America,POPULATION:4890379
task2.js:17 COUNTRY NAME:Croatia,REGION:Europe,SUB REGION:Southern Europe,POPULATION:4190669
task2.js:17 COUNTRY NAME:Cuba,REGION:Americas,SUB REGION:Caribbean,POPULATION:11239004
task2.js:17 COUNTRY NAME:Curaçao,REGION:Americas,SUB REGION:Caribbean,POPULATION:154843
task2.js:17 COUNTRY NAME:Cyprus,REGION:Europe,SUB REGION:Southern Europe,POPULATION:847000
task2.js:17 COUNTRY NAME:Czech Republic,REGION:Europe,SUB REGION:Eastern Europe,POPULATION:10558524
task2.js:17 COUNTRY NAME:Denmark,REGION:Europe,SUB REGION:Northern Europe,POPULATION:5717014
task2.js:17 COUNTRY NAME:Djibouti,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:900000
task2.js:17 COUNTRY NAME:Dominica,REGION:Americas,SUB REGION:Caribbean,POPULATION:71293
task2.js:17 COUNTRY NAME:Dominican Republic,REGION:Americas,SUB REGION:Caribbean,POPULATION:10075045
task2.js:17 COUNTRY NAME:Ecuador,REGION:Americas,SUB REGION:South America,POPULATION:16545799
task2.js:17 COUNTRY NAME:Egypt,REGION:Africa,SUB REGION:Northern Africa,POPULATION:91290000
task2.js:17 COUNTRY NAME:El Salvador,REGION:Americas,SUB REGION:Central America,POPULATION:6520675
task2.js:17 COUNTRY NAME:Equatorial Guinea,REGION:Africa,SUB REGION:Middle Africa,POPULATION:1222442
task2.js:17 COUNTRY NAME:Eritrea,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:5352000
task2.js:17 COUNTRY NAME:Estonia,REGION:Europe,SUB REGION:Northern Europe,POPULATION:1315944
task2.js:17 COUNTRY NAME:Ethiopia,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:92206005
task2.js:17 COUNTRY NAME:Falkland Islands (Malvinas),REGION:Americas,SUB REGION:South America,POPULATION:2563
task2.js:17 COUNTRY NAME:Faroe Islands,REGION:Europe,SUB REGION:Northern Europe,POPULATION:49376
task2.js:17 COUNTRY NAME:Fiji,REGION:Oceania,SUB REGION:Melanesia,POPULATION:867000
task2.js:17 COUNTRY NAME:Finland,REGION:Europe,SUB REGION:Northern Europe,POPULATION:5491817
task2.js:17 COUNTRY NAME:France,REGION:Europe,SUB REGION:Western Europe,POPULATION:66710000
task2.js:17 COUNTRY NAME:French Guiana,REGION:Americas,SUB REGION:South America,POPULATION:254541
task2.js:17 COUNTRY NAME:French Polynesia,REGION:Oceania,SUB REGION:Polynesia,POPULATION:271800
task2.js:17 COUNTRY NAME:French Southern Territories,REGION:Africa,SUB REGION:Southern Africa,POPULATION:140
task2.js:17 COUNTRY NAME:Gabon,REGION:Africa,SUB REGION:Middle Africa,POPULATION:1802278
task2.js:17 COUNTRY NAME:Gambia,REGION:Africa,SUB REGION:Western Africa,POPULATION:1882450
task2.js:17 COUNTRY NAME:Georgia,REGION:Asia,SUB REGION:Western Asia,POPULATION:3720400
task2.js:17 COUNTRY NAME:Germany,REGION:Europe,SUB REGION:Western Europe,POPULATION:81770900
task2.js:17 COUNTRY NAME:Ghana,REGION:Africa,SUB REGION:Western Africa,POPULATION:27670174
task2.js:17 COUNTRY NAME:Gibraltar,REGION:Europe,SUB REGION:Southern Europe,POPULATION:33140
task2.js:17 COUNTRY NAME:Greece,REGION:Europe,SUB REGION:Southern Europe,POPULATION:10858018
task2.js:17 COUNTRY NAME:Greenland,REGION:Americas,SUB REGION:Northern America,POPULATION:55847
task2.js:17 COUNTRY NAME:Grenada,REGION:Americas,SUB REGION:Caribbean,POPULATION:103328
task2.js:17 COUNTRY NAME:Guadeloupe,REGION:Americas,SUB REGION:Caribbean,POPULATION:400132
task2.js:17 COUNTRY NAME:Guam,REGION:Oceania,SUB REGION:Micronesia,POPULATION:184200
task2.js:17 COUNTRY NAME:Guatemala,REGION:Americas,SUB REGION:Central America,POPULATION:16176133
task2.js:17 COUNTRY NAME:Guernsey,REGION:Europe,SUB REGION:Northern Europe,POPULATION:62999
task2.js:17 COUNTRY NAME:Guinea,REGION:Africa,SUB REGION:Western Africa,POPULATION:12947000
task2.js:17 COUNTRY NAME:Guinea-Bissau,REGION:Africa,SUB REGION:Western Africa,POPULATION:1547777
task2.js:17 COUNTRY NAME:Guyana,REGION:Americas,SUB REGION:South America,POPULATION:746900
task2.js:17 COUNTRY NAME:Haiti,REGION:Americas,SUB REGION:Caribbean,POPULATION:11078033
task2.js:17 COUNTRY NAME:Heard Island and McDonald Islands,REGION:,SUB REGION:,POPULATION:0
task2.js:17 COUNTRY NAME:Holy See,REGION:Europe,SUB REGION:Southern Europe,POPULATION:451
task2.js:17 COUNTRY NAME:Honduras,REGION:Americas,SUB REGION:Central America,POPULATION:8576532
task2.js:17 COUNTRY NAME:Hong Kong,REGION:Asia,SUB REGION:Eastern Asia,POPULATION:7324300
task2.js:17 COUNTRY NAME:Hungary,REGION:Europe,SUB REGION:Eastern Europe,POPULATION:9823000
task2.js:17 COUNTRY NAME:Iceland,REGION:Europe,SUB REGION:Northern Europe,POPULATION:334300
task2.js:17 COUNTRY NAME:India,REGION:Asia,SUB REGION:Southern Asia,POPULATION:1295210000
task2.js:17 COUNTRY NAME:Indonesia,REGION:Asia,SUB REGION:South-Eastern Asia,POPULATION:258705000
task2.js:17 COUNTRY NAME:Côte d'Ivoire,REGION:Africa,SUB REGION:Western Africa,POPULATION:22671331
task2.js:17 COUNTRY NAME:Iran (Islamic Republic of),REGION:Asia,SUB REGION:Southern Asia,POPULATION:79369900
task2.js:17 COUNTRY NAME:Iraq,REGION:Asia,SUB REGION:Western Asia,POPULATION:37883543
task2.js:17 COUNTRY NAME:Ireland,REGION:Europe,SUB REGION:Northern Europe,POPULATION:6378000
task2.js:17 COUNTRY NAME:Isle of Man,REGION:Europe,SUB REGION:Northern Europe,POPULATION:84497
task2.js:17 COUNTRY NAME:Israel,REGION:Asia,SUB REGION:Western Asia,POPULATION:8527400
task2.js:17 COUNTRY NAME:Italy,REGION:Europe,SUB REGION:Southern Europe,POPULATION:60665551
task2.js:17 COUNTRY NAME:Jamaica,REGION:Americas,SUB REGION:Caribbean,POPULATION:2723246
task2.js:17 COUNTRY NAME:Japan,REGION:Asia,SUB REGION:Eastern Asia,POPULATION:126960000
task2.js:17 COUNTRY NAME:Jersey,REGION:Europe,SUB REGION:Northern Europe,POPULATION:100800
task2.js:17 COUNTRY NAME:Jordan,REGION:Asia,SUB REGION:Western Asia,POPULATION:9531712
task2.js:17 COUNTRY NAME:Kazakhstan,REGION:Asia,SUB REGION:Central Asia,POPULATION:17753200
task2.js:17 COUNTRY NAME:Kenya,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:47251000
task2.js:17 COUNTRY NAME:Kiribati,REGION:Oceania,SUB REGION:Micronesia,POPULATION:113400
task2.js:17 COUNTRY NAME:Kuwait,REGION:Asia,SUB REGION:Western Asia,POPULATION:4183658
task2.js:17 COUNTRY NAME:Kyrgyzstan,REGION:Asia,SUB REGION:Central Asia,POPULATION:6047800
task2.js:17 COUNTRY NAME:Lao People's Democratic Republic,REGION:Asia,SUB REGION:South-Eastern Asia,POPULATION:6492400
task2.js:17 COUNTRY NAME:Latvia,REGION:Europe,SUB REGION:Northern Europe,POPULATION:1961600
task2.js:17 COUNTRY NAME:Lebanon,REGION:Asia,SUB REGION:Western Asia,POPULATION:5988000
task2.js:17 COUNTRY NAME:Lesotho,REGION:Africa,SUB REGION:Southern Africa,POPULATION:1894194
task2.js:17 COUNTRY NAME:Liberia,REGION:Africa,SUB REGION:Western Africa,POPULATION:4615000
task2.js:17 COUNTRY NAME:Libya,REGION:Africa,SUB REGION:Northern Africa,POPULATION:6385000
task2.js:17 COUNTRY NAME:Liechtenstein,REGION:Europe,SUB REGION:Western Europe,POPULATION:37623
task2.js:17 COUNTRY NAME:Lithuania,REGION:Europe,SUB REGION:Northern Europe,POPULATION:2872294
task2.js:17 COUNTRY NAME:Luxembourg,REGION:Europe,SUB REGION:Western Europe,POPULATION:576200
task2.js:17 COUNTRY NAME:Macao,REGION:Asia,SUB REGION:Eastern Asia,POPULATION:649100
task2.js:17 COUNTRY NAME:Macedonia (the former Yugoslav Republic of),REGION:Europe,SUB REGION:Southern Europe,POPULATION:2058539
task2.js:17 COUNTRY NAME:Madagascar,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:22434363
task2.js:17 COUNTRY NAME:Malawi,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:16832910
task2.js:17 COUNTRY NAME:Malaysia,REGION:Asia,SUB REGION:South-Eastern Asia,POPULATION:31405416
task2.js:17 COUNTRY NAME:Maldives,REGION:Asia,SUB REGION:Southern Asia,POPULATION:344023
task2.js:17 COUNTRY NAME:Mali,REGION:Africa,SUB REGION:Western Africa,POPULATION:18135000
task2.js:17 COUNTRY NAME:Malta,REGION:Europe,SUB REGION:Southern Europe,POPULATION:425384
task2.js:17 COUNTRY NAME:Marshall Islands,REGION:Oceania,SUB REGION:Micronesia,POPULATION:54880
task2.js:17 COUNTRY NAME:Martinique,REGION:Americas,SUB REGION:Caribbean,POPULATION:378243
task2.js:17 COUNTRY NAME:Mauritania,REGION:Africa,SUB REGION:Western Africa,POPULATION:3718678
task2.js:17 COUNTRY NAME:Mauritius,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:1262879
task2.js:17 COUNTRY NAME:Mayotte,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:226915
task2.js:17 COUNTRY NAME:Mexico,REGION:Americas,SUB REGION:Central America,POPULATION:122273473
task2.js:17 COUNTRY NAME:Micronesia (Federated States of),REGION:Oceania,SUB REGION:Micronesia,POPULATION:102800
task2.js:17 COUNTRY NAME:Moldova (Republic of),REGION:Europe,SUB REGION:Eastern Europe,POPULATION:3553100
task2.js:17 COUNTRY NAME:Monaco,REGION:Europe,SUB REGION:Western Europe,POPULATION:38400
task2.js:17 COUNTRY NAME:Mongolia,REGION:Asia,SUB REGION:Eastern Asia,POPULATION:3093100
task2.js:17 COUNTRY NAME:Montenegro,REGION:Europe,SUB REGION:Southern Europe,POPULATION:621810
task2.js:17 COUNTRY NAME:Montserrat,REGION:Americas,SUB REGION:Caribbean,POPULATION:4922
task2.js:17 COUNTRY NAME:Morocco,REGION:Africa,SUB REGION:Northern Africa,POPULATION:33337529
task2.js:17 COUNTRY NAME:Mozambique,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:26423700
task2.js:17 COUNTRY NAME:Myanmar,REGION:Asia,SUB REGION:South-Eastern Asia,POPULATION:51419420
task2.js:17 COUNTRY NAME:Namibia,REGION:Africa,SUB REGION:Southern Africa,POPULATION:2324388
task2.js:17 COUNTRY NAME:Nauru,REGION:Oceania,SUB REGION:Micronesia,POPULATION:10084
task2.js:17 COUNTRY NAME:Nepal,REGION:Asia,SUB REGION:Southern Asia,POPULATION:28431500
task2.js:17 COUNTRY NAME:Netherlands,REGION:Europe,SUB REGION:Western Europe,POPULATION:17019800
task2.js:17 COUNTRY NAME:New Caledonia,REGION:Oceania,SUB REGION:Melanesia,POPULATION:268767
task2.js:17 COUNTRY NAME:New Zealand,REGION:Oceania,SUB REGION:Australia and New Zealand,POPULATION:4697854
task2.js:17 COUNTRY NAME:Nicaragua,REGION:Americas,SUB REGION:Central America,POPULATION:6262703
task2.js:17 COUNTRY NAME:Niger,REGION:Africa,SUB REGION:Western Africa,POPULATION:20715000
task2.js:17 COUNTRY NAME:Nigeria,REGION:Africa,SUB REGION:Western Africa,POPULATION:186988000
task2.js:17 COUNTRY NAME:Niue,REGION:Oceania,SUB REGION:Polynesia,POPULATION:1470
task2.js:17 COUNTRY NAME:Norfolk Island,REGION:Oceania,SUB REGION:Australia and New Zealand,POPULATION:2302
task2.js:17 COUNTRY NAME:Korea (Democratic People's Republic of),REGION:Asia,SUB REGION:Eastern Asia,POPULATION:25281000
task2.js:17 COUNTRY NAME:Northern Mariana Islands,REGION:Oceania,SUB REGION:Micronesia,POPULATION:56940
task2.js:17 COUNTRY NAME:Norway,REGION:Europe,SUB REGION:Northern Europe,POPULATION:5223256
task2.js:17 COUNTRY NAME:Oman,REGION:Asia,SUB REGION:Western Asia,POPULATION:4420133
task2.js:17 COUNTRY NAME:Pakistan,REGION:Asia,SUB REGION:Southern Asia,POPULATION:194125062
task2.js:17 COUNTRY NAME:Palau,REGION:Oceania,SUB REGION:Micronesia,POPULATION:17950
task2.js:17 COUNTRY NAME:Palestine, State of,REGION:Asia,SUB REGION:Western Asia,POPULATION:4682467
task2.js:17 COUNTRY NAME:Panama,REGION:Americas,SUB REGION:Central America,POPULATION:3814672
task2.js:17 COUNTRY NAME:Papua New Guinea,REGION:Oceania,SUB REGION:Melanesia,POPULATION:8083700
task2.js:17 COUNTRY NAME:Paraguay,REGION:Americas,SUB REGION:South America,POPULATION:6854536
task2.js:17 COUNTRY NAME:Peru,REGION:Americas,SUB REGION:South America,POPULATION:31488700
task2.js:17 COUNTRY NAME:Philippines,REGION:Asia,SUB REGION:South-Eastern Asia,POPULATION:103279800
task2.js:17 COUNTRY NAME:Pitcairn,REGION:Oceania,SUB REGION:Polynesia,POPULATION:56
task2.js:17 COUNTRY NAME:Poland,REGION:Europe,SUB REGION:Eastern Europe,POPULATION:38437239
task2.js:17 COUNTRY NAME:Portugal,REGION:Europe,SUB REGION:Southern Europe,POPULATION:10374822
task2.js:17 COUNTRY NAME:Puerto Rico,REGION:Americas,SUB REGION:Caribbean,POPULATION:3474182
task2.js:17 COUNTRY NAME:Qatar,REGION:Asia,SUB REGION:Western Asia,POPULATION:2587564
task2.js:17 COUNTRY NAME:Republic of Kosovo,REGION:Europe,SUB REGION:Eastern Europe,POPULATION:1733842
task2.js:17 COUNTRY NAME:Réunion,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:840974
task2.js:17 COUNTRY NAME:Romania,REGION:Europe,SUB REGION:Eastern Europe,POPULATION:19861408
task2.js:17 COUNTRY NAME:Russian Federation,REGION:Europe,SUB REGION:Eastern Europe,POPULATION:146599183
task2.js:17 COUNTRY NAME:Rwanda,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:11553188
task2.js:17 COUNTRY NAME:Saint Barthélemy,REGION:Americas,SUB REGION:Caribbean,POPULATION:9417
task2.js:17 COUNTRY NAME:Saint Helena, Ascension and Tristan da Cunha,REGION:Africa,SUB REGION:Western Africa,POPULATION:4255
task2.js:17 COUNTRY NAME:Saint Kitts and Nevis,REGION:Americas,SUB REGION:Caribbean,POPULATION:46204
task2.js:17 COUNTRY NAME:Saint Lucia,REGION:Americas,SUB REGION:Caribbean,POPULATION:186000
task2.js:17 COUNTRY NAME:Saint Martin (French part),REGION:Americas,SUB REGION:Caribbean,POPULATION:36979
task2.js:17 COUNTRY NAME:Saint Pierre and Miquelon,REGION:Americas,SUB REGION:Northern America,POPULATION:6069
task2.js:17 COUNTRY NAME:Saint Vincent and the Grenadines,REGION:Americas,SUB REGION:Caribbean,POPULATION:109991
task2.js:17 COUNTRY NAME:Samoa,REGION:Oceania,SUB REGION:Polynesia,POPULATION:194899
task2.js:17 COUNTRY NAME:San Marino,REGION:Europe,SUB REGION:Southern Europe,POPULATION:33005
task2.js:17 COUNTRY NAME:Sao Tome and Principe,REGION:Africa,SUB REGION:Middle Africa,POPULATION:187356
task2.js:17 COUNTRY NAME:Saudi Arabia,REGION:Asia,SUB REGION:Western Asia,POPULATION:32248200
task2.js:17 COUNTRY NAME:Senegal,REGION:Africa,SUB REGION:Western Africa,POPULATION:14799859
task2.js:17 COUNTRY NAME:Serbia,REGION:Europe,SUB REGION:Southern Europe,POPULATION:7076372
task2.js:17 COUNTRY NAME:Seychelles,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:91400
task2.js:17 COUNTRY NAME:Sierra Leone,REGION:Africa,SUB REGION:Western Africa,POPULATION:7075641
task2.js:17 COUNTRY NAME:Singapore,REGION:Asia,SUB REGION:South-Eastern Asia,POPULATION:5535000
task2.js:17 COUNTRY NAME:Sint Maarten (Dutch part),REGION:Americas,SUB REGION:Caribbean,POPULATION:38247
task2.js:17 COUNTRY NAME:Slovakia,REGION:Europe,SUB REGION:Eastern Europe,POPULATION:5426252
task2.js:17 COUNTRY NAME:Slovenia,REGION:Europe,SUB REGION:Southern Europe,POPULATION:2064188
task2.js:17 COUNTRY NAME:Solomon Islands,REGION:Oceania,SUB REGION:Melanesia,POPULATION:642000
task2.js:17 COUNTRY NAME:Somalia,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:11079000
task2.js:17 COUNTRY NAME:South Africa,REGION:Africa,SUB REGION:Southern Africa,POPULATION:55653654
task2.js:17 COUNTRY NAME:South Georgia and the South Sandwich Islands,REGION:Americas,SUB REGION:South America,POPULATION:30
task2.js:17 COUNTRY NAME:Korea (Republic of),REGION:Asia,SUB REGION:Eastern Asia,POPULATION:50801405
task2.js:17 COUNTRY NAME:South Sudan,REGION:Africa,SUB REGION:Middle Africa,POPULATION:12131000
task2.js:17 COUNTRY NAME:Spain,REGION:Europe,SUB REGION:Southern Europe,POPULATION:46438422
task2.js:17 COUNTRY NAME:Sri Lanka,REGION:Asia,SUB REGION:Southern Asia,POPULATION:20966000
task2.js:17 COUNTRY NAME:Sudan,REGION:Africa,SUB REGION:Northern Africa,POPULATION:39598700
task2.js:17 COUNTRY NAME:Suriname,REGION:Americas,SUB REGION:South America,POPULATION:541638
task2.js:17 COUNTRY NAME:Svalbard and Jan Mayen,REGION:Europe,SUB REGION:Northern Europe,POPULATION:2562
task2.js:17 COUNTRY NAME:Swaziland,REGION:Africa,SUB REGION:Southern Africa,POPULATION:1132657
task2.js:17 COUNTRY NAME:Sweden,REGION:Europe,SUB REGION:Northern Europe,POPULATION:9894888
task2.js:17 COUNTRY NAME:Switzerland,REGION:Europe,SUB REGION:Western Europe,POPULATION:8341600
task2.js:17 COUNTRY NAME:Syrian Arab Republic,REGION:Asia,SUB REGION:Western Asia,POPULATION:18564000
task2.js:17 COUNTRY NAME:Taiwan,REGION:Asia,SUB REGION:Eastern Asia,POPULATION:23503349
task2.js:17 COUNTRY NAME:Tajikistan,REGION:Asia,SUB REGION:Central Asia,POPULATION:8593600
task2.js:17 COUNTRY NAME:Tanzania, United Republic of,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:55155000
task2.js:17 COUNTRY NAME:Thailand,REGION:Asia,SUB REGION:South-Eastern Asia,POPULATION:65327652
task2.js:17 COUNTRY NAME:Timor-Leste,REGION:Asia,SUB REGION:South-Eastern Asia,POPULATION:1167242
task2.js:17 COUNTRY NAME:Togo,REGION:Africa,SUB REGION:Western Africa,POPULATION:7143000
task2.js:17 COUNTRY NAME:Tokelau,REGION:Oceania,SUB REGION:Polynesia,POPULATION:1411
task2.js:17 COUNTRY NAME:Tonga,REGION:Oceania,SUB REGION:Polynesia,POPULATION:103252
task2.js:17 COUNTRY NAME:Trinidad and Tobago,REGION:Americas,SUB REGION:Caribbean,POPULATION:1349667
task2.js:17 COUNTRY NAME:Tunisia,REGION:Africa,SUB REGION:Northern Africa,POPULATION:11154400
task2.js:17 COUNTRY NAME:Turkey,REGION:Asia,SUB REGION:Western Asia,POPULATION:78741053
task2.js:17 COUNTRY NAME:Turkmenistan,REGION:Asia,SUB REGION:Central Asia,POPULATION:4751120
task2.js:17 COUNTRY NAME:Turks and Caicos Islands,REGION:Americas,SUB REGION:Caribbean,POPULATION:31458
task2.js:17 COUNTRY NAME:Tuvalu,REGION:Oceania,SUB REGION:Polynesia,POPULATION:10640
task2.js:17 COUNTRY NAME:Uganda,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:33860700
task2.js:17 COUNTRY NAME:Ukraine,REGION:Europe,SUB REGION:Eastern Europe,POPULATION:42692393
task2.js:17 COUNTRY NAME:United Arab Emirates,REGION:Asia,SUB REGION:Western Asia,POPULATION:9856000
task2.js:17 COUNTRY NAME:United Kingdom of Great Britain and Northern Ireland,REGION:Europe,SUB REGION:Northern Europe,POPULATION:65110000
task2.js:17 COUNTRY NAME:United States of America,REGION:Americas,SUB REGION:Northern America,POPULATION:323947000
task2.js:17 COUNTRY NAME:Uruguay,REGION:Americas,SUB REGION:South America,POPULATION:3480222
task2.js:17 COUNTRY NAME:Uzbekistan,REGION:Asia,SUB REGION:Central Asia,POPULATION:31576400
task2.js:17 COUNTRY NAME:Vanuatu,REGION:Oceania,SUB REGION:Melanesia,POPULATION:277500
task2.js:17 COUNTRY NAME:Venezuela (Bolivarian Republic of),REGION:Americas,SUB REGION:South America,POPULATION:31028700
task2.js:17 COUNTRY NAME:Viet Nam,REGION:Asia,SUB REGION:South-Eastern Asia,POPULATION:92700000
task2.js:17 COUNTRY NAME:Wallis and Futuna,REGION:Oceania,SUB REGION:Polynesia,POPULATION:11750
task2.js:17 COUNTRY NAME:Western Sahara,REGION:Africa,SUB REGION:Northern Africa,POPULATION:510713
task2.js:17 COUNTRY NAME:Yemen,REGION:Asia,SUB REGION:Western Asia,POPULATION:27478000
task2.js:17 COUNTRY NAME:Zambia,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:15933883
task2.js:17 COUNTRY NAME:Zimbabwe,REGION:Africa,SUB REGION:Eastern Africa,POPULATION:14240168
*/